Routine
ebarrera95/fitgoal pull request #10
Opened 2020-03-10 03:58 UTC by ebarrera95

2020-03-10 05:18 UTC, rlaguilar requested changes

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal.xcodeproj/project.pbxproj
> +		05B2E20B240F95AF009B0443 /* HomeViewController + UICollectionViewDelegateFlowLayout.swift in Sources */ = {isa = PBXBuildFile; fileRef = 05B2E20A240F95AF009B0443 /* HomeViewController + UICollectio
We forgot to remove the space in the file name at the end of this line `UICollectionViewDelegateFlowLayout .swift` while resolving conflicts.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExerciseCell.swift
> +    var backgroundImage: UIImageView = {
Remember to mark all these views as private

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExerciseCell.swift
> +
Space

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +
Spaces

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +    func reloadCellData(exercises: [Exercise]) {
Move this function below to the section corresponding to the functions.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +    var exercisesDelegate: RoutineDelegate?
Delegates should always be `weak`.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +    var routineCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())
If you don't need to mutate the collection view (i.e. assign other instance of collection view to it) you should use `let` instead of `var`. There are other variables with this issue as well in this file.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +        routineCollectionView.backgroundColor = .clear
You want to set the background color when you create the collection view, not every time you resize it.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/ExploreRoutineCell.swift
> +        let cell = routineCollectionView.dequeueReusableCell(withReuseIdentifier: "Cell Exercise", for: indexPath) as! ExerciseCell
You should use `ExerciseCell.identifier` for the reuse identifier instead of `"Cell Exercise"`

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/GoalTrakerCell.swift
> +        addSubviewsToContentView(views: subviews)
👏

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController.swift
> +    }
You probably need to rethink the concept you want to express with this, because these names are hard to understand. In the meantime, `vissible` is a typo, you don't need the double _s_. 

A suggestion for the enum. Apparently, what you want to do with it is to express what's the current user routine. So a possible option would be:

```swift
enum UserRoutine {
    case unset
    case exploring(Routine)
}
```

By having an associated value for the `. exploring` case you can get rid of the optional routine value in the home view controller.

Maybe the names I used are not the most appropriate, I was just giving an example.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +            return routineDetails == .vissible ? 1 : 0
You should always avoid comparing enum values like this, because if you add a new case to the enum you won't know the places where you need to update the code to keep it consistent. For example, if you add a case called `partial`, this code will return 0 for that new case too, and that may not be the behaviour you want. 

In cases like these you have to options: switch over the enum value the same way you are switching over the home section enum, or you can create a variable as part of the enum to express what you want. For example, in this case your enum definition would look like:

```swift
enum RoutineDetails {
    case visible, hidden
    
    var requiresVisibleElements {
        switch self {
            case .visible: 
                return true
            case .hidden:
                return false
    }
}
```

And then you this line you could do something like: `return routineDetails.requiresVisibleElements ? 1 : 0`. This way you keep the code in this place short and still have the advantages of getting a compiler error when you add a new case in the enum. (Remind me to talk you about this with more details later).

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +                .dequeueReusableCell(withReuseIdentifier: "Routines Cell", for: indexPath) as? ExploreRoutineCell else {
You should use `ExploreRoutineCell.identifier` instead of `"Routines Cell"`.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +            if routineDetails == .vissible {
In this case you don't need the comparison, because if you are asked for a cell that means the collection view should be visible.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +                cell.reloadCellData(exercises: allExersices)
This way of passing the data isn't very clear. You might consider something like:

```swift
cell.display(routine: routineToDisplay, availableExercises: allExercises)
```

Doing this you cat get rid of the optional routine value inside the cell. Also note that you have a typo in the name `allExersices`.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/SuggestedRoutineCell.swift
> +    var delegate: RoutineDelegate?
The delegate should be weak.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +     func collectionView(
You don't need the space before the `func`.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDelegateFlowLayout.swift
> +            return routineDetails == .hidden ? .zero : CGSize(width: view.bounds.width - 32, height: 248)
Same here, avoid comparing with enum values.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDelegateFlowLayout.swift
> +             return routineDetails == .hidden ? .zero : CGSize(width: view.bounds.width - 32, height: 72)
Same, do not compare with enum values.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController.swift
> +    var routineCellDelegate: RoutineDelegate?
All this properties should be private

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/HomeViewController.swift
> +    func fetchExersices() {
Typo: Should be `Exercises`.

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/SuggestedRoutineCell.swift
> +protocol RoutineDelegate {
The instance of the delegate inside the cell should be weak. To do that you need to declare the protocol as:

```swift 
protocol RoutineDelegate: AnyObject {
    ...
}
```

2020-03-10 05:18 UTC, rlaguilar commented on FitGoal/FitGoal/URL+.swift
> +            }
The responsibility of this function is to download an image. It shouldn't have to interact with the cache at all. That responsibility should be passed to the fetch image function.

2020-03-10 05:46 UTC, ebarrera95 commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +            return routineDetails == .vissible ? 1 : 0
True! Thanks. I was looking for a way to avoid a switch inside another switch. I forgot about this option :-)

2020-03-11 00:26 UTC, ebarrera95 commented on FitGoal/FitGoal/HomeViewController + UICollectionViewDataSource.swift
> +                cell.reloadCellData(exercises: allExersices)
I change this method according to your suggestions, but I can't see a way to totally get rid of the optional value inside the cell. Did you mean, get rid of having to check for the optional value **inside** the function? 
(I'm almost sure you didn't)

2020-03-11 02:31 UTC, rlaguilar approved these changes
🎉 Thanks for fixing the changes in different commits. It was very easy to review.

2020-03-11 02:54 UTC, merged