Settings#2 account info cells
ebarrera95/fitgoal pull request #27
Opened 2020-05-14 02:06 UTC by ebarrera95

2020-05-14 09:54 UTC, rlaguilar requested changes

2020-05-14 09:54 UTC, rlaguilar commented on FitGoal/FitGoal/Setting/AccountInfoCell.swift
> +            if cellTitle == "Notifications" {
You shouldn't use the value of the title for this, try to use a specific property for that configuration. Once we add localisation for the app this code won't work anymore.

2020-05-14 09:54 UTC, rlaguilar commented on FitGoal/FitGoal/Setting/AccountInfoCell.swift
> +    let cellTitleLabel = UILabel()
Private?

2020-05-14 09:54 UTC, rlaguilar commented on FitGoal/FitGoal/Setting/SettingsViewController.swift
> +enum SettingsTableViewSection: Int, CaseIterable {
Private?

2020-05-15 00:15 UTC, ebarrera95 commented on FitGoal/FitGoal/Setting/SettingsViewController.swift
> +}
So these are the changes that I propose. Downside: It's a new `enum`.  What do you recond? It's almost always the solution that comes to my mind when I face a problem like this.

2020-05-18 02:44 UTC, rlaguilar approved these changes

2020-05-18 06:51 UTC, merged