Image fetcher
ebarrera95/fitgoal pull request #37
Opened 2020-06-03 23:36 UTC by ebarrera95

I created this object because, throughout the app, feting images is a repetitive process so here I'm putting all the logic together to reuse it in several places. 
As an example of what refactoring classes that fetch images would look like, I did it with `DetailViewController`

2020-06-04 05:09 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ExerciseImageFetcherDelegate.swift
> +class ExerciseImageFetcherDelegate: NSObject, ImageFetcherDelegate {
Use name that reflects the purpose of the object instead of the protocols it implements.

2020-06-04 05:09 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ExerciseImageFetcherDelegate.swift
> +    }
Reuse function to configure fetching state.

2020-06-04 05:10 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ExerciseImageFetcherDelegate.swift
> +        assertionFailure("Couldn't fetch image with error \(error)")
This is no place for assertion failure.

2020-06-04 05:10 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +var imageCache: [URL: UIImage] = [:]
Mark this field as private or move it into the ImageFetcher type.

2020-06-04 05:11 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +    func imageFetcherIsInProgress()
Improve the name of this function to match the other functions in the protocol. It should indicate that the fetching operation started.

2020-06-04 05:11 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +                delegate?.imageFetcherIsInProgress()
Ensure this path is reached.

2020-06-04 05:11 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +    init(url: URL) {
Move the initializer to a function only place.

2020-06-04 05:12 UTC, ebarrera95 commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +        return imageURL.fetchImage { result in
Check if the image is already cached here and remove the corresponding code in the URL extension.

2020-06-06 00:15 UTC, rlaguilar requested changes

2020-06-06 00:15 UTC, rlaguilar commented on FitGoal/FitGoal/ImageFetcher/ImageFetcher.swift
> +    init(url: URL?) {
You don't handle `nil` urls, so the parameter shouldn't be optional.

2020-06-06 00:49 UTC, rlaguilar approved these changes

2020-06-06 00:53 UTC, merged